### ISSUE TITLE
Demo not working.

### ISSUE THREAD

**Issue by tomgreenhill** [mshwery/minimal-lightbox#15]
I guess not a huge issue as such, but the paths/assets are wrong and the demo doesn't work. Would be nice to be able to see what the script look like and how it works for installing.

Nice one!
Tom

**Comment by mshwery** [comment]
Hm have you tried compiling the project first?

The build files are excluded from version control intentionally.

If you install via npm they should be present.

**Comment by tomgreenhill** [comment]
Apologies I was too hasty to comment! Thanks for pointing this out, despite the fact I should've noticed myself! It's been a long week! Great work.

Thanks again!

**Comment by mshwery** [comment]
Thanks for opening the issue. The readme could be improved in outlining usage instructions when cloned from GitHub to make this clearer.
